styles/styles.css

Fix #1
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/2023/february/vt-showcases-proof-points-on-freight-efficiency-sustainability-and-maximizing-uptime-at-tmc-2023
- After: https://issue-1--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/2023/february/vt-showcases-proof-points-on-freight-efficiency-sustainability-and-maximizing-uptime-at-tmc-2023

add default styling

---

blocks/cards-hero/cards-hero.css
blocks/cards-hero/cards-hero.js

Fix #2
Test URLs:
- After: https://issue-2--vg-volvotrucks-us--hlxsites.hlx.page/

cards hero

---

blocks/teaser-grid/teaser-grid.css

Test URLs:
- After: https://fix-teaser-grid-modifiers--vg-volvotrucks-us--hlxsites.hlx.page/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vah/
- After: https://fix-teaser-grid-modifiers--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vah/

fix: updated teaser-grid modifiers to cover additional cases easier

---

blocks/teaser-cards/teaser-cards.css
blocks/teaser-grid/teaser-grid.css
styles/styles.css

Fix #33 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vah/
- After: https://teaser-cards-4--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vah/

feat: 4 col teaser cards with link list on mobile

---

blocks/carousel/carousel.css

Fix #10
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page
- After: https://issue-10-fix-padding--vg-volvotrucks-us--hlxsites.hlx.page

unset padding for first and last element for grid layout

---

helix-query.yaml

Fix #6 
Test URLs:
- After: https://6-index-of-press-releases--vg-volvotrucks-us--hlxsites.hlx.page/

add full and press release index

---

blocks/teaser-cards/teaser-cards.css
blocks/teaser-cards/teaser-cards.js
styles/styles.css

Fix #28 
Test URLs:
- Before: https://main--vg-volvotracuks-us--hlxsites.hlx.page/
- After: https://teaser-cards-1--vg-volvotrucks-us--hlxsites.hlx.page/
- Before: https://main--vg-volvotracuks-us--hlxsites.hlx.page/drafts/drudolph/vah/
- After: https://teaser-cards-1--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vah/

feat: teaser with one column

---

scripts/scripts.js
styles/styles.css

Fix #32 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vah/
- After: https://section-bg--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vah/

feat: section backgrounds

---

blocks/tabbed-carousel/tabbed-carousel.js

Test URLs:
- Before: https://issue-23--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnr-carousel
- After: https://issue-23-scroll--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnr-carousel

fix: tabbed carousel scroll indicator

---

blocks/tabbed-carousel/tabbed-carousel.css
blocks/tabbed-carousel/tabbed-carousel.js
scripts/scripts.js

Fix #23 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnr-carousel
- After: https://issue-23--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnr-carousel

Tabbed Carousel Block

---

blocks/tabbed-carousel/tabbed-carousel.css
blocks/tabbed-carousel/tabbed-carousel.js
scripts/scripts.js

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnr-carousel
- After: https://tabbed-carousel-full-width--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnr-carousel

fix: tabbed carousel full width

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js

Fix #52
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/powertrain/d13tc/
- After: https://issue-52--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/powertrain/d13tc/

fix: center carousel grid items

---

helix-query.yaml

Test URLs:
- After: https://issue-publish-date--vg-volvotrucks-us--hlxsites.hlx.page/

feat: add publish date to press release index

---

blocks/press-release-disclaimer/press-release-disclaimer.css
blocks/press-release-disclaimer/press-release-disclaimer.js

Fix #57 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/jlledo/press-releases/press-demo
- After: https://57-press-release-disclaimer--vg-volvotrucks-us--hlxsites.hlx.page/drafts/jlledo/press-releases/press-demo

#57 disclaimer block read content from a document

---

helix-query.yaml

Fix #76 
Test URLs:
- After: https://76-pr-and-magazine-index-updates--vg-volvotrucks-us--hlxsites.hlx.live/

new indexes and fields

---

blocks/footer/footer.css
blocks/footer/footer.js

Fix #70
Test URLs:
- After: https://footer-link-target--vg-volvotrucks-us--hlxsites.hlx.page/

fix: link target in footer and missing scroll to top

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js

Fix #49
Test URLs:
- After: https://carousel-item-sizing--vg-volvotrucks-us--hlxsites.hlx.page/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/powertrain/d13tc/
- After: https://carousel-item-sizing--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/powertrain/d13tc/
- After: https://carousel-item-sizing--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/
- After: …

fix: carousel item sizing and desktop controls

---

blocks/footer/footer.css

Fix #82
Test URLs:
- After: https://footer-list-alignment--vg-volvotrucks-us--hlxsites.hlx.page/

fix: remove list padding in footer

---

blocks/key-facts/key-facts.css

Fix #85 
Test URLs:
- After: https://85-defect-keyfacts-text-styling--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/

#85 key-facts text is correctly styled

---

blocks/sub-nav/sub-nav.css
blocks/sub-nav/sub-nav.js
helix-query.yaml
scripts/scripts.js
styles/styles.css

Fix #65
Yet missing is the stickiness - will be done in a different issue as we wait for the main nav to be finished.
Test URLs:
- After: https://sub-navigation--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/specifications/
- After: https://sub-navigation--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/specifications/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/vnr-electric-contact/
- After: …

feat: sub navigation

---

blocks/embed/embed.css
blocks/embed/embed.js
scripts/scripts.js
styles/styles.css

Fix #63 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/
- After: https://63-embeded-videos--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/

63 embeded videos

---

tools/sidekick/config.json
tools/tagger/index.html
tools/tagger/tagger.css
tools/tagger/tagger.js

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/tools/tagger/index.html
- After: https://tagger-tool--vg-volvotrucks-us--hlxsites.hlx.page/tools/tagger/index.html

feat: add tagger extension for sidekick

---

helix-query.yaml

Test URLs:
- After: https://index-press-releases-tags--vg-volvotrucks-us--hlxsites.hlx.page/

feat: add tags to press releases index

---

helix-query.yaml

Test URLs:
- After: https://issue-content-index--vg-volvotrucks-us--hlxsites.hlx.page/

feat: add main section to press release index

---

helix-query.yaml
tools/importer/import.js

Test URLs:
- After: https://index-update-1--vg-volvotrucks-us--hlxsites.hlx.page/

Index update 1

---

tools/importer/import.js

Fix 
Test URLs:
- After: https://3-import-content--vg-volvotrucks-us--hlxsites.hlx.live/

wip for import - now with tags!

---

blocks/header/header.css
blocks/header/header.js
blocks/sub-nav/sub-nav.css
blocks/sub-nav/sub-nav.js
scripts/lib-franklin.js
scripts/scripts.js
styles/styles.css
tools/importer/import.js

Fix #73
Test URLs:
- After: https://navigation-stickiness--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/

feat: navigation stickiness

---

blocks/fragment/fragment.css
blocks/fragment/fragment.js

Test URLs:
- After: https://add-fragment-block--vg-volvotrucks-us--hlxsites.hlx.live/

add Fragment block (from Block Library)

---

blocks/specifications/specifications.css
blocks/specifications/specifications.js

Fix #114
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnl/specifications/
- After:  https://specifications--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnl/specifications/

fix: specification styles when changing active column on mobile

---

styles/styles.css

Fix #118 
Test URLs:
- After: https://118-main-margin--vg-volvotrucks-us--hlxsites.hlx.page/

fix: add margin to main area on desktop

---

helix-query.yaml

Fix #54
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/
- After: https://54-article-content--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/
Added the text content to allow for text search of articles.

added attribute to article index

---

blocks/header/header.css

Fix #119
Test URLs:
- After: https://font-nav-section--vg-volvotrucks-us--hlxsites.hlx.page/

fix: font size in header nav and logo section

---

scripts/scripts.js

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/wingeier/our-difference/uptime-and-connectivity/
- After: https://hero-first-section--vg-volvotrucks-us--hlxsites.hlx.page/drafts/wingeier/our-difference/uptime-and-connectivity/

Only decorate the first section as Hero block

---

scripts/scripts.js

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/wingeier/our-difference/uptime-and-connectivity/
- After: https://decorateHyperlinkImages--vg-volvotrucks-us--hlxsites.hlx.page/drafts/wingeier/our-difference/uptime-and-connectivity/

automatically decorate Hyperlink Images

---

blocks/hero/hero.css
blocks/teaser-cards/teaser-cards.css
styles/styles.css

Fix #118
Test URLs:
- After: https://fix-hero-top-margin--vg-volvotrucks-us--hlxsites.hlx.page/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/
- After: https://fix-hero-top-margin--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/

fix: hero top margin

---

blocks/teaser-cards/teaser-cards.css

Fix #146
Test URLs:
- After: https://fix-teaser-headings--vg-volvotrucks-us--hlxsites.hlx.page/

fix: teaser heading margins

---

blocks/text/text.css
styles/styles.css

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/
- After: https://text-style--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/

add some styling options to the text block

---

blocks/header/header.js

Fix #158 
Test URLs:
- After: https://158-link-logo-tohome-page--vg-volvotrucks-us--hlxsites.hlx.page/

158 link logo in navbar to homepage

---

blocks/hero/hero.css

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/trucks/
- After: https://fix-hero-max-height--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/trucks/

fix: set hero max height

---

blocks/text/text.css
scripts/scripts.js
styles/styles.css

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/trucks/vnr/
- After: https://feat-page-style-center--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/trucks/vnr/

feat: page style center

---

styles/styles.css

Fix #173
Test URLs:
- After: https://fix-subnav-overlaps-flyout--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/

fix: subnav overlaps flyout

---

blocks/eloqua-form/eloqua-form.js
scripts/scripts.js
styles/styles.css

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vhd/
- After: https://fix-elq-form-with-section-bg--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vhd/

fix: section background with eloqua forms

---

blocks/document-list/document-list.css
blocks/document-list/document-list.js

Fix #193
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/wiring-diagrams/
- After: https://193-block-document-list--vg-volvotrucks-us--hlxsites.hlx.live/parts-and-services/services/body-builder-support/wiring-diagrams/

193 block document list

---

blocks/columns/columns.css
blocks/tabbed-accordion/tabbed-accordion.css
blocks/tabbed-carousel/tabbed-carousel.css
blocks/tabbed-carousel/tabbed-carousel.js
scripts/scripts.js
styles/styles.css

Fix #197
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vhd/interior/
- After: https://fix-tabbed-carousel-full-width--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vhd/interior/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vah/features/
- After: https://fix-tabbed-carousel-full-width--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vah/features/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vah/
- After: https://fix-tabbed-carousel-full-width--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vah/

fix: various style adjustments to carousel and tabbed features

---

blocks/header/header.css

Fix #143 
Test URLs:
- After: https://143-defect-search-bar-is-different--vg-volvotrucks-us--hlxsites.hlx.page/

143 defect search bar is different

---

blocks/carousel/carousel.js

Test URLs:
- After: https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/

fix: carousel link styles with new format

---

blocks/teaser-cards/teaser-cards.js

Fix https://github.com/hlxsites/vg-volvotrucks-us/issues/168
Test URLs:
Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/wingeier/issues-168
After: https://fix-teaser-with-yt-link--vg-volvotrucks-us--hlxsites.hlx.page/drafts/wingeier/issues-168

fix: teaser Cards (with Video) plain link to youtube does not work

---

helix-query.yaml

Fix #207 
Test URLs:
- After: https://207-body-builder-news--vg-volvotrucks-us--hlxsites.hlx.live/

207 body builder news - index

---

blocks/header/header.js

Fix #211
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/
- After: https://nav-lang--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/

Fix header language detection 

---

styles/lazy-styles.css

Secondary header should not be italic
Test URLs:
- After: https://h2-em--vg-volvotrucks-us--hlxsites.hlx.page/

Secondary header should not be italic

---

blocks/specifications/specifications.js

Fix #224
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnl/specifications/
- After: https://224-format-text-in-table--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnl/specifications/

#224 Fix formating text in table

---

blocks/carousel/carousel.css
blocks/carousel/carousel.js
blocks/teaser-cards/teaser-cards.css

Fix #<189>
Test URLs:
- After: https://189-fix-arrow-missing-carousel--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/
Used existing button class for arrows

189 fix arrow missing carousel

---

blocks/teaser-cards/teaser-cards.css
styles/lazy-styles.css

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/innovation/electromobility/
- After: https://teaser-card-icons--vg-volvotrucks-us--hlxsites.hlx.page/innovation/electromobility/

teaser-cards: don't scale up icons 

---

blocks/body-builder-news/body-builder-news.js
blocks/teaser-grid/teaser-grid.css
styles/styles.css

Fixes #281 
Fixes #280
Test URLs:
- After: https://fix-teaser-grid-header--vg-volvotrucks-us--hlxsites.hlx.page/
- After: https://fix-teaser-grid-header--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/

fix: teaser grid hero on mobile

---

blocks/download-images/download-images.js
styles/lazy-styles.css

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/jlledo/press-releases/press-release-demo
- After: https://simplify-download-images--vg-volvotrucks-us--hlxsites.hlx.page/drafts/jlledo/press-releases/press-release-demo

download-images: remove link checking, always download original, remove additional link creation

---

scripts/scripts.js

Reverts hlxsites/vg-volvotrucks-us#249
This seems to break cases like https://main--vg-volvotrucks-us--hlxsites.hlx.page/about-volvo/facilities/reman-center/

Revert "make hero structure more flexible"

---

blocks/photosphere/photosphere.css
blocks/photosphere/photosphere.js
scripts/scripts.js

Fix #196 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/photo-sphere
- After: https://196-photosphere-block--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/photo-sphere
- After: https://196-photosphere-block--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vhd/interior/

196 photosphere block

---

scripts/scripts.js

Fix #293
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/links
- After: https://target-blank-links--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/links
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/about-volvo/facilities/reman-center/
- After: https://target-blank-links--vg-volvotrucks-us--hlxsites.hlx.page/about-volvo/facilities/reman-center/

feat: open external links and pdfs in new tab

---

blocks/iframe/iframe.css
blocks/iframe/iframe.js

Fix #256 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/request-for-assistance/
- After: https://256-iframe--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/request-for-assistance/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/remote-programming/registration/
- After: https://256-iframe--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/remote-programming/registration/

256 iframe

---

scripts/delayed.js

Fix #291 
Test URLs:
- After: https://291-gtm-integration--vg-volvotrucks-us--hlxsites.hlx.live/
this fix also includes FaceBook pixel tracking

add FaceBook pixel and GA

---

scripts/scripts.js

Fix #315
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-shift-transmission/i-see/
- After: https://315-mp4-only--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-shift-transmission/i-see/

fix #315: play mp4 if there is no youtube link

---

blocks/magazine-articles/magazine-articles.css
scripts/lib-ffetch.js

Fix #319
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/
- After: https://fix-ajax-4-pr-and-magazine--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/
- After: https://fix-ajax-4-pr-and-magazine--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/

feat: support reload-less pagination and filter

---

styles/styles.css

in the document file, I added a section metadata with the style: center to be able to center it
Fix #215 point 6
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/parts/genuine/engine/
- After: https://215-6-center-text-alignment-style--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/parts/genuine/engine/

#215-6 add section center style metadata

---

styles/styles.css

Reverts hlxsites/vg-volvotrucks-us#324

Revert "#215-6 add section center style metadata"

---

blocks/body-builder-news/body-builder-news.css

Fix #320 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/news-and-events/
- After: https://320-bb--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/news-and-events/

fix spacing

---

blocks/sub-nav/sub-nav.js

Fix #14
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnl/specifications/
- After: https://14-nav--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnl/specifications/

fix 14: open build link in sub-nav in new window

---

scripts/delayed.js

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.live/cookies/
- After: https://cookie--vg-volvotrucks-us--hlxsites.hlx.live/cookies/
In the new branch, when pressing accept it will not reload the page any more if not necessary.

update OneTrust Cookies Consent Notice

---

blocks/header/header.css

Fix #352 
Test URLs:
- After: https://352-hide-nav-suggestions--vg-volvotrucks-us--hlxsites.hlx.page/

#352 Hide nav search suggestions

---

blocks/related-articles/related-articles.js
templates/magazine/magazine.css

Fix #359 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/denney-story/
- After: https://359-related-article--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/denney-story/

fix #359 removed filter and centered header

---

blocks/eloqua-form/forms/ContactUsVolvo.html

Fix #362 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/about-volvo/contact-us/contact-us-form/
- After: https://362-contact-form--vg-volvotrucks-us--hlxsites.hlx.page/about-volvo/contact-us/contact-us-form/
Also added a little space between the checkbox and text, just above the submit button.

removed last contact field

---

tools/sidekick/config.json

based on https://github.com/adobe/franklin-sidekick-library
After merging, a new `library` button appears in sharepoint. 
After: https://main--vg-volvotrucks-us--hlxsites.hlx.page/

Add Block library

---

blocks/header/header.js

Test URLs:
- After: https://acessibilty-enhance--vg-volvotrucks-us--hlxsites.hlx.page/

add some accessibility features

---

scripts/scripts.js

Fix #376 
Test URLs:
- After: https://376-youtube-video-cookies--vg-volvotrucks-us--hlxsites.hlx.page/

376 Update reading external cookie consent video

---

blocks/header/header.css

Fix #375 
Test URLs:
- After: https://375-nav-search-suggestions--vg-volvotrucks-us--hlxsites.hlx.page/

375 nav search suggestions

---

.github/workflows/publish-notifier.yaml
helix-query.yaml

Fix #389 
New publish-notifier github action for the AEM Connector
New Index in helix-query.yaml for the AEM Connector pull

389 search connector integration

---

.github/workflows/publish-notifier.yaml

Fix #390
https://390-search-connector-integration--vg-volvotrucks-us--hlxsites.hlx.page/
https://main--vg-macktrucks-com--hlxsites.hlx.page/
Fix variable issue in publish-notifier

fix publish-notifier variable

---

blocks/photosphere/photosphere.js
placeholder.json

Fix #383 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/photo-sphere
- After: https://383-add-message-to-photosphere--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/photo-sphere

#383 Add message to photosphere

---

blocks/magazine-articles/magazine-articles.js
blocks/press-releases/press-releases.js
blocks/related-articles/related-articles.js

Fix #397 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/
- After: https://fix-js-date--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/

add timezone offset to correct article dates

---

.github/workflows/publish-notifier.yaml
.github/workflows/unpublish-notifier.yaml

Add unpublish github-action notifier
Update github actions to add curl requests
Fix #403 
Test URLs:
- After: https://403-search-connector-to-api--vg-volvotrucks-us--hlxsites.hlx.page/

403 search connector to api

---

.github/workflows/publish-notifier.yaml
.github/workflows/unpublish-notifier.yaml

* update upsert parameters
* update delete parameters
Fix #407
Test URLs:
- After: https://407-update-search-connector-1--vg-volvotrucks-us--hlxsites.hlx.page/

update upsert parameters

---

.github/workflows/publish-notifier.yaml
.github/workflows/unpublish-notifier.yaml

Fix sed path parameter
Fix #407
Test URLs:
- After: https://407-update-search-connector-1--vg-volvotrucks-us--hlxsites.hlx.page/

fix replace path sed

---

.github/workflows/publish-notifier.yaml
.github/workflows/unpublish-notifier.yaml

Add api-key parameter on requests
Fix #413 
Test URLs:
- After: https://413-search-connector-api-key--vg-volvotrucks-us--hlxsites.hlx.page/

add api-key parameter on request

---

blocks/eloqua-form/eloqua-form.css
blocks/eloqua-form/forms/event-from.html

Fix #430 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/test
- After: https://430-adding-eloqua-event-form--vg-volvotrucks-us--hlxsites.hlx.page/drafts/tdziezyk/test

#430 Add event form

---

blocks/eloqua-form/forms/event-from.html

Fix #430 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/designed-to-change-everything/
- After: https://430-adding-eloqua-event-form--vg-volvotrucks-us--hlxsites.hlx.page/trucks/designed-to-change-everything/

#430 Label change

---

blocks/eloqua-form/forms/event-from.html

Fix #430
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/designed-to-change-everything/
- After: https://430-adding-eloqua-event-form--vg-volvotrucks-us--hlxsites.hlx.page/trucks/designed-to-change-everything/

#430 Css fix

---

blocks/eloqua-form/forms/event-from.html

Fix #430 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/designed-to-change-everything/
- After: https://430-reset-hidden-fields--vg-volvotrucks-us--hlxsites.hlx.page/trucks/designed-to-change-everything/

#430 Reset hidden fields

---

styles/styles.css

Fix #444 
Test URLs:
- After: https://444-homepage-grid--vg-volvotrucks-us--hlxsites.hlx.page/

#444 Limit blue contract css

---

scripts/delayed.js

Fix #447 
Test URLs:
- After: https://447-update-gtm-code-volvo--vg-volvotrucks-us--hlxsites.hlx.page/

447 update gtm code volvo

---

scripts/delayed.js

Fix #447 
Test URLs:
- After: https://447-update-gtm-code-volvo--vg-volvotrucks-us--hlxsites.hlx.page/

Updated GTM client call with new GA4 provided function

---

blocks/eloqua-form/eloqua-form.css
blocks/eloqua-form/eloqua-form.js
placeholder.json
scripts/delayed.js
scripts/scripts.js

Fix #457 
Test URLs:
- After: https://457-facebook-script--vg-volvotrucks-us--hlxsites.hlx.page/

457 facebook script

---

blocks/nhtsa-header/nhtsa-header.css
blocks/nhtsa-header/nhtsa-header.js
blocks/vin-number/vin-number.css
blocks/vin-number/vin-number.js
placeholder.json

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/recalls/
- After: https://471-nhtsa-accordion-styling--vg-volvotrucks-us--hlxsites.hlx.page/recalls/

NHTSA changes

---

blocks/vin-number/vin-number.css
blocks/vin-number/vin-number.js
placeholder.json

Fix #496 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/recalls/
- After: https://496-prodqa-url--vg-volvotrucks-us--hlxsites.hlx.page/recalls/

Add Prod url and implement refresh date 496, 498, 502

---

blocks/vin-number/vin-number.css
blocks/vin-number/vin-number.js
placeholder.json

Fix 545
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/recalls/
- After: https://545-add-make--vg-volvotrucks-us--hlxsites.hlx.page/recalls/

Add model and make 545

---

blocks/eloqua-form/eloqua-form.js
blocks/v2-livestream-embed/v2-livestream-embed.js
scripts/common.js
scripts/constants.js
scripts/delayed.js
scripts/video-helper.js

Fix #535 
Test URLs:
- After: https://535-engagement-tracking--vg-volvotrucks-us--hlxsites.hlx.page/

Adding Engagement tracking script

---

scripts/common.js
styles/header-font.css

Fix #520 
Test URLs:
- After: https://520-font-delay--vg-volvotrucks-us--hlxsites.hlx.page/

Font loading delay

---

.github/workflows/publish-notifier.yaml
.github/workflows/unpublish-notifier.yaml

Fix #582 
Test URLs:
- After: https://582-search-api-update-backend--vg-volvotrucks-us--hlxsites.hlx.page/

change search connector for opensearch endpoint

---

blocks/vin-number/vin-number.js

Fix #573 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/recalls/
- After: https://573-581-recalls-changes--vg-volvotrucks-us--hlxsites.hlx.page/recalls/

573,581 fix recalls capitialization and change validation for regex

---

helix-query.yaml

Fix #596 
Test URLs:
- After: https://596-update-search-helix-query--vg-volvotrucks-us--hlxsites.hlx.page/

helix-qeuery update search field names

---

.github/pull_request_template.md
blocks/get-an-offer/get-an-offer.js
blocks/teaser-cards/teaser-cards.js
blocks/v2-banner/v2-banner.js
blocks/v2-content-card/v2-content-card.js
blocks/v2-dealer-locator-teaser/v2-dealer-locator-teaser.js
blocks/v2-event-notify/v2-event-notify.js
blocks/v2-hero/v2-hero.js
blocks/v2-inpage-navigation/v2-inpage-navigation.css
blocks/v2-inpage-navigation/v2-inpage-navigation.js
blocks/v2-media-gallery/v2-media-gallery.js
blocks/v2-resource-gallery/v2-resource-gallery.js
blocks/v2-section-header/v2-section-header.js
blocks/v2-truck-lineup/v2-truck-lineup.js
blocks/v2-video/v2-video.js
news-and-stories/press-releases/feed.xml
scripts/lib-franklin.js
scripts/scripts.js
styles/styles.css

Fix #625
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/drafts/alan/buttons
- After: https://625-refactor-buttons-for-helix-5--vg-volvotrucks-us--hlxsites.aem.page/drafts/alan/buttons
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/drafts/alan/buttons-v2
- After: https://625-refactor-buttons-for-helix-5--vg-volvotrucks-us--hlxsites.aem.page/drafts/alan/buttons-v2

Refactor how the buttons classes are added #625

---

.github/release.yml
scripts/scripts.js

Test URLs:
- After: https://fix-buttons-decoration--vg-volvotrucks-us--hlxsites.aem.page/

Fix how buttons/links are decorated

---

styles/styles.css

Fix https://github.com/hlxsites/vg-volvotrucks-us/issues/657
Test URLs:
Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/trucks/vnl/v2/#safety
After: https://657-refactoring-vnl-modals--vg-volvotrucks-us--hlxsites.aem.page/trucks/vnl/v2/#safety

Remove redesign v2 modal overrides #657

---

blocks/v2-visual-grid/v2-visual-grid.css
blocks/v2-visual-grid/v2-visual-grid.js

Fix #634
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/block-library/blocks/v2-visual-grid
- After: https://634-v2-visual-grid--vg-volvotrucks-us--hlxsites.aem.page/block-library/blocks/v2-visual-grid

[v2-visual-grid]: Add magazine article variant #634

---

blocks/v2-visual-grid/v2-visual-grid.css
blocks/v2-visual-grid/v2-visual-grid.js
package-lock.json
package.json

Test URLs:
- After: https://release-18--vg-volvotrucks-us--hlxsites.aem.page/

Release 18

---

blocks/v2-text/v2-text.css
blocks/v2-text/v2-text.js
styles/styles.css
templates/v2-magazine/v2-magazine.css

Fix #633
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/drafts/alan/v2-magazine-article
- After: https://633-magazine-article-typography--vg-volvotrucks-us--hlxsites.aem.page/drafts/alan/v2-magazine-article

Apply redesign typography on magazine article #633

---

blocks/v2-article-cards/v2-article-cards.css
blocks/v2-article-cards/v2-article-cards.js
placeholder.json

Fix #680
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/drafts/shomps/v2-article-cards
- After: https://680-articles-feed--vg-volvotrucks-us--hlxsites.aem.page/drafts/shomps/v2-article-cards

Magazine article cards dynamic feed #680

---

blocks/header/header.js
constants.json
scripts/common.js
tools/sidekick/tools-config.js

Test URLs:
- After: https://constants-file-check--vg-volvotrucks-us--hlxsites.aem.page/

Constants file checks added

---

blocks/v2-article-cards/v2-article-cards.css
blocks/v2-article-cards/v2-article-cards.js

Fix #681
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/drafts/shomps/repeated-articles
- After: https://681-preventing-duplicate-articles--vg-volvotrucks-us--hlxsites.aem.page/drafts/shomps/repeated-articles

Preventing duplicate articles from appearing in dynamic article list #681

---

blocks/v2-stories-carousel/v2-stories-carousel.css
blocks/v2-stories-carousel/v2-stories-carousel.js

Fix #545
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/block-library/blocks/v2-stories-carousel
- After: https://545-stories-carousel-changes--vg-volvotrucks-us--hlxsites.aem.page/block-library/blocks/v2-stories-carousel

Stories Carousel design changes #545

---

common/modal/modal.js

Reverts hlxsites/vg-volvotrucks-us#723
This was supposed to go to develop first, let's revert it to ensure the proper order

Revert "Blank page displayed when clicked on Explore safety link for the second time #698"

---

.github/ci/generate-news-feed-config.js
.github/ci/generate-news-feed.js
.github/workflows/generate-atom-news-feed.yaml
constants.json
scripts/common.js

Fix #710 
Test URLs:
- After: https://710-news-config-migration--vg-volvotrucks-us--hlxsites.aem.page/

Move news feed GH action variables from GH to constants file.

---

blocks/vin-number/vin-number.js
scripts/common.js

Fix #676 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/fr/recalls/
- After: https://bug-nhtsa-676--vg-volvotrucks-us--hlxsites.aem.page/fr/recalls/

NHTSA Search Bar Displaying Incorrect Text #676

---

.github/ci/generate-news-feed-config.js
.github/ci/generate-news-feed.js
.github/workflows/generate-atom-news-feed.yaml
blocks/vin-number/vin-number.js
common/modal/modal.js
constants.json
package-lock.json
package.json
scripts/common.js

Test URLs:
- After: https://release-21--vg-volvotrucks-us--hlxsites.aem.page/

Release 21

---

constants.json
head.html
scripts/common.js
scripts/scripts.js
scripts/validate-countries.js
styles/styles.css

Fix #704
Integrated logic from macktrucks embedded configurator solution https://github.com/hlxsites/vg-macktrucks-com/pull/647/files while removing what doesn't seem to be needed for volvotrucks

NFR: Change Truck Configurator iFrame Integration to Enhanced Embed Solution #704

---

blocks/v2-social-block/v2-social-block.css

Fix #540
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/drafts/shomps/v2-social
- After: https://540-social-block-changes--vg-volvotrucks-us--hlxsites.aem.page/drafts/shomps/v2-social

Social block changes #540

---

blocks/v2-embed/v2-embed.js
blocks/v2-video/v2-video.js

- https://fix-v2-video--vg-volvotrucks-us--hlxsites.aem.page/drafts/zoe/v2-video
- https://fix-v2-video--vg-volvotrucks-us--hlxsites.aem.page/news-and-stories/volvo-trucks-magazine-v2/cover-story-designed-to-change-everything/
- Before: 
- https://main--vg-volvotrucks-us--hlxsites.aem.page/drafts/zoe/v2-video
- https://main--vg-volvotrucks-us--hlxsites.aem.page/news-and-stories/volvo-trucks-magazine-v2/cover-story-designed-to-change-everything/

Fix v2 video block

---

blocks/v2-embed/v2-embed.js

Fix #870
- https://fix-embed-block--vg-volvotrucks-us--hlxsites.aem.page/trucks/vnr/interior
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/trucks/vnr/interior

Fix embed block

---

styles/styles.css

Fix #704 
Needed to test fixes related to #704 in develop since it can't be previewed at https://704-discrepancy-fixes--vg-volvotrucks-us--hlxsites.hlx.page/drafts/luka/truck-builder
Since this feature already found its way into develop branch I need to make it stable, therefore I submit this intermittent PR. There will probably need to be one more depending on testing outcomes and the alignment with Zoe about requirements

704 discrepancy fixes

---

scripts/scripts.js
styles/styles.css

- https://691-new-volvo--volvotrucks-na--aemsites.hlx.page/
- Before: https://main--volvotrucks-us--volvogroup.aem.page/

704 input fixes

---

.github/ci/generate-news-feed.js

* fixed newsfeed function
- https://691-new-volvo--volvotrucks-na--aemsites.hlx.page/
- Before: https://main--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- Before: https://main--volvotrucks-ca--volvogroup.aem.page/
- After: https://<branch>--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- Before: https://main--volvotrucks-mx--volvogroup.aem.page/
- After: https://<branch>--volvotrucks-mx--volvogroup.aem.page/

Update develop from main for the release

---

blocks/magazine-articles/magazine-articles.js

- https:/hotfix-magazine-search--volvotrucks-na--aemsites.hlx.page/
- Before: https://main--volvotrucks-us--volvogroup.aem.page/
Other markets:
Canada:
- Before: https://main--volvotrucks-ca--volvogroup.aem.page/
- After: https://hotfix-magazine-search--volvotrucks-ca--volvogroup.aem.page/
Mexico:
- Before: https://main--volvotrucks-mx--volvogroup.aem.page/
- After: https://hotfix-magazine-search--volvotrucks-mx--volvogroup.aem.page/

Hotfix magazine search

---

head.html

Fix: #762
- After: https://762-bug-website--vg-volvotrucks-us--hlxsites.hlx.page/

Revert dynamic preloading constants file #762
