- helix-query.yaml
Test URLs:
- After: https://press-release-index-description--vg-volvotrucks-us--hlxsites.hlx.page/
> feat: add description to press release index, remove unused template

- blocks/press-releases/press-releases.js
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/
- After: https://date-string-press-releases--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/
> fix: display correct date string in press overview

- blocks/header/header.css
Fix #120
Test URLs:
- After: https://margin-navigation-bar--vg-volvotrucks-us--hlxsites.hlx.page/
> fix: margin of main nav items, jumping arrows active/passive

- blocks/teaser-cards/teaser-cards.css
Fix #147 
Please be aware that this is not a pixel perfect match for all the cases on the original site.
Test URLs:
- After: https://teaser-cards-gap--vg-volvotrucks-us--hlxsites.hlx.page/
> fix: teaser cards gap

- blocks/carousel/carousel.js
The carousel does not properly initialise when it shares a section with other blocks loaded asynchronously as the item and container width default to `auto` until the section is actually loaded / show. 
Instead of using a timeout I used now a mutation observer that triggers the toggle once the section is set to loaded.
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnr/
- After: https://fix-carousel-init--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnr/
> fix: initialise carousel after section loaded

- blocks/header/header.css
Fix #141
Test URLs:
- After: https://nav-tools-gap--vg-volvotrucks-us--hlxsites.hlx.page/
> fix: text wrap in navigation tools on mobile

- helix-sitemap.yaml
Add a helix-sitemap.yaml, to generate a sitemap at /sitemap.xml. I think this needs to be merged into main before the sitemap starts populating.
Fix #16
Test URLs:
- After: https://issue-16--vg-volvotrucks-us--hlxsites.hlx.page/
> feat: added helix-sitemap.yaml

- blocks/sub-nav/sub-nav.css
- styles/styles.css
With throttling enabled to slow 3g the dark sub navigation background is positioned on top of the header and shifting down after the navigation content loaded. With this change the sub navigation is fixed to the bottom of the header always.
Test URLs:
- After: https://fix-sub-nav-background-shift--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/
> fix: subnav background moves after content loaded

- blocks/teaser-cards/teaser-cards.js
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/trucks/
- After: https://fix-teaser-cards-1-cta--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/trucks/
> fix: enforce secondary cta not in 1 column teaser cards

- blocks/sub-nav/sub-nav.css
- helix-query.yaml
Fix #225 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/
- After: https://sub-nav-filter--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/
The width of the 1st element in the sub-nav should be limited to 110px and centered.
Excluded /**/sub-nav from the index.
> excluded sub-nav from index and updated css for 1st element

- blocks/key-facts/key-facts.css
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnx/performance/
- After: https://fix-space-before-trailingline--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnx/performance/
> fix: add missing space above trailing line

- blocks/specifications/specifications.css
- blocks/specifications/specifications.js
instead of having multiple styles, it can be used the same style across all faq content.
in the following folder: "/parts-and-services/services/faqs/" is plain content, so instead of this I used a draft one "/drafts/jlledo/faqs-demo" that should fit all cases.
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/jlledo/faqs-demo
- After: https://160-block-faq-accordion--vg-volvotrucks-us--hlxsites.hlx.page/drafts/jlledo/faqs-demo
> #160 specification block used to be the faq block

- blocks/specifications/specifications.js
From the import sheet https://www.volvotrucks.us/parts-and-services/services/uptime-service-solutions/diagnostic-tools/
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/uptime-service-solutions/diagnostic-tools/
- After: https://spec-table-head-wo-img--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/uptime-service-solutions/diagnostic-tools/
Should still work for:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/specifications/
- After: https://spec-table-head-wo-img--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/specifications/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/features/
- After: https://spec-table-head-wo-img--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/f …
> feat: spec table header without images for multiple columns

- blocks/specifications/specifications.js
- blocks/teaser-cards/teaser-cards.js
- scripts/scripts.js
- styles/styles.css
This moves the link into the the image `<p>` instead of moving the image into another `<p>`, which in the later iteration is removed (considering the links are separated by a `<br>`)
It also center-aligns the play button on hover.
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/meet-your-volvo/
- After: https://fix-teaser-cards-video--vg-volvotrucks-us--hlxsites.hlx.page/trucks/meet-your-volvo/
> fix: teaser cards with videos

- blocks/press-releases/press-releases.css
- blocks/press-releases/press-releases.js
- helix-query.yaml
- scripts/lib-ffetch.js
Fix #258
Fix #290
This adds support for:
- latest (3) press releases, optionally by tag
- either as list (default) or as cards (when added to the class list)
- featured list of press releases
Featured Press Releases:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-torque/
- After: https://featured-press-releases--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-torque/
Latest Press Releases:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/
- After: https://featured-press-releases--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/
Press Releases:
- Before: …
> feat: featured press releases

- blocks/teaser-grid/teaser-grid.css
- blocks/teaser-grid/teaser-grid.js
Reduces the use of `position: absolute` to improve automatic sizing of the grid and grid cells and positioning of the elements.
Add support to grow grid cells on mobile viewport when the text is too big.
Add support for single column style (text justifies centered and supports left/right alignment with slightly different margins and a max width of the text box on desktop)
Test URLs:
- After: https://teaser-grid-text-pos-xs--vg-volvotrucks-us--hlxsites.hlx.page/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/active-driver-assist
- After: https://teaser-grid-text-pos-xs--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/active-driver-assist
> fix: teaser grid text position and grow on mobile

- blocks/header/header.js
- scripts/scripts.js
Test: the link is in the nav: trucks: `Build Your VNL`
Fix #14
Test URLs:
- After: https://14-open-build-in-new-tab--vg-volvotrucks-us--hlxsites.hlx.page/
> Open links to https://build.volvotrucks.us/ in new tab

- blocks/press-releases/press-releases.js
Fix #258
The limit applied in the press-releases.js returned only the first 3 press releases without taking the active filters into account.   Now the limit is applied with a filter already at load time.
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-torque/
- After: https://latestpr-w-filter--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-torque/
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/
- After: https://latestpr-w-filter--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/
> fix: add load time filtering for pr block with tags

- scripts/scripts.js
Fix #337
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/wingeier/wrong-link
- After: https://337-images-not-linked--vg-volvotrucks-us--hlxsites.hlx.page/drafts/wingeier/wrong-link
> fix #337: use link href and ignore link text if they differ. Link the image instead of printing a standalone link. 

- templates/article/article.css
- templates/article/article.js
Fix #358 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/2023/april/volvo-trucks-to-exhibit-industry-leading-sustainable-freight-transport-solutions-and-supporting-ecosystem-at-act-expo-2023/
- After: https://358-pd-missing-on-prs--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/2023/april/volvo-trucks-to-exhibit-industry-leading-sustainable-freight-transport-solutions-and-supporting-ecosystem-at-act-expo-2023/
> add press date

- scripts/scripts.js
Fix #364
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/calendar/
- After: https://364-image-download--vg-volvotrucks-us--hlxsites.hlx.page/trucks/calendar/
- Reference site: https://us.vtnaprod-cm.na.volvogroup.com/trucks/calendar/
Created the page with thumbnails that link to high res images.
Clicking on the image or the month link will download the high res image.
Did not add the download icon overlay.
> set target for jpeg to _blank

- blocks/eloqua-form/eloqua-form.js
- templates/magazine/magazine.js
eloqua forms load with an intersection observer, which means that only loads if there are present in the viewport, so is needed to add a temporal id attribute to its block father element to enable the anchor navigation to do the trick
Fix #392 
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/cover-story/
- After: https://392-subscribe-button-not-working--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/cover-story/
> #392 subscribe button jump to the form

- helix-query.yaml
Update helix-search search index to handle tags and categories
Fix #417 
Test URLs:
- After: https://417-search-connector-add-tags--vg-volvotrucks-us--hlxsites.hlx.page/
> 417 search connector add tags

- blocks/body-builder-news/body-builder-news.js
- blocks/magazine-articles/magazine-articles.js
- blocks/press-releases/press-releases.js
- blocks/related-articles/related-articles.js
- news-and-stories/press-releases/feed.xml
- scripts/delayed.js
- scripts/lib-franklin.js
- scripts/scripts.js
- tools/sidekick/config.json
- tools/sidekick/library.html
This PR migrates the `volvotrucks-us` site to the new full screen version of the sidekick library.
@synox Most blocks worked without change, some required changes due to `window.location.origin` not existing when running in the sidekick library.
Two blocks need to be slightly reworked.
- Calculator
- Engine Specifications
These blocks assume the content to feed them is in the same place as the page itself. It doesn't look like this pattern is going to work. I would suggest to rework these blocks to instead configure them using block config and read in the values using the `readBlockConfig` method from `lib-franklin`.
Test URLs:
- After: https://sidekick-library-migration--vg-volvotrucks-us--hlxsites.hlx.page/
> fix: migration to new sidekick library

- tools/sidekick/library.html
Forgot some css to hide the sidekick when the library is opened
Test URLs:
Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/
After: https://hide-sidekick--vg-volvotrucks-us--hlxsites.hlx.page/
> fix: hide sidekick when library is open

- scripts/delayed.js
Fix #453 
Test URLs:
- After: https://453-gtm-tracking--vg-volvotrucks-us--hlxsites.hlx.page/
> #453 Loading GTM tracking only when user agrees

- scripts/delayed.js
FB pixel is no longer triggered by GTM, so now only delayed.js will trigger it under the Social Media cookie allowance
#
Fix #457 
Test URLs:
- After: https://457-fbevents-triggering--vg-volvotrucks-us--hlxsites.hlx.page/
> 457 fb pixel only trigger if social cookie is on

- blocks/v2-article-cards/v2-article-cards.css
- blocks/v2-article-cards/v2-article-cards.js
- placeholder.json
Fix #619
Created the variants where the author adds the link and the text of the button. The styles depend on the amount of links added. For 1, 2 and 3 links per block.
The rest comes from matching the link with the metadata from the articles. 
[Figma](https://www.figma.com/design/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?node-id=1569-17870&m=dev)
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/drafts/shomps/v2-article-cards
- After: https://619-article-cards--vg-volvotrucks-us--hlxsites.aem.page/drafts/shomps/v2-article-cards
> Article cards 1 and 2 link variations #619

- common/modal/modal.js
Fix #698
Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/trucks/all-new-vnl/#safety
- After: https://698-modal-content-visibility--vg-volvotrucks-us--hlxsites.aem.page/trucks/all-new-vnl/#safety
The issue was that section gets stuck on its loading status, which hides its content before it is loaded, supposedly to prevent the flash of un-styled content (FOUC)
The fix is based on re-checking the section status when the video has been loaded. There is a bit of delay before video shows up after modal is closed and re-opened. This is expected behavior.
> Blank page displayed when clicked on Explore safety link for the second time #698

- helix-query.yaml
Add missing fields from magazines to search
Fix #532
Test URLs:
- After: https://532-fr-volvo-trucks-magazine-search-filter-tags--vg-volvotrucks-us--hlxsites.aem.page/
> 532 - add magazines metadata to search

- blocks/v2-stories-carousel/v2-stories-carousel.css
- blocks/v2-stories-carousel/v2-stories-carousel.js
Fix #541
Test URLs:
- After: https://541-stories-carusel-variant--vg-volvotrucks-us--hlxsites.aem.page/
The related-articles variant for stories carousel was added to https://541-stories-carusel-variant--vg-volvotrucks-us--hlxsites.aem.page/drafts/luka/driving-the-future/ where it appears above newsletter subscription. 
It looks the same as the original stories one, but it filters article selection by tags. If the limit is 7, it will first show 7 articles matching the first tag of the currently open article. If there are less such articles than the limit, articles with second tag will be added and so on.
> FR: [V2 Stories Carousel] Variant - Related Articles #541

- head.html
- scripts/common.js
Fix #733
Note:
In order to check this functionality in **actual multi-language sites**, I created the branch `TESTING` in the Canada Repository.
For each language the site should retrieve one or the other `constants.xlsx` file
Link here: 
https://testing--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/ --> or /fr-ca/ 
Test URLs:
- After: https://733-multi-lang-config--vg-volvotrucks-us--hlxsites.aem.page/
> Multi language sites constants file location #733

- blocks/v2-article-cards/v2-article-cards.css
Fix #702 
-Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/shomps/v2-article-cards
-After: https://702-remove-all-caps--vg-volvotrucks-us--hlxsites.hlx.page/drafts/shomps/v2-article-cards
> Remove all caps from article cards block #702

- blocks/magazine-articles/magazine-articles.css
- blocks/magazine-articles/magazine-articles.js
- blocks/search/autosuggest.js
- blocks/search/search.js
- blocks/vin-number/vin-number.js
- placeholder.json
- scripts/common.js
- scripts/delayed.js
- scripts/magazine-press.js
- scripts/search-api.js
Use search API to update the article's list so every change in the filter is a new API call, not only once at the beginning
- Fix an issue related to general Search #720
- Fix a pagination bug 
That occurs after changing the pagination to a page number greater than the amount of the next results needed it doesn't show any item if the results don't bring results. Now, when the user does a new filtering, it updates the page again to page 1
To test the bug, go to a pagination page, like page 3 or more, and change the filters to another value, e.g. filter by another truck. It should go to pagination 1 including the URL parameter
#
Fix #688, #720
- Before: https://main--vg-volvotrucks-us--hlxsites.aem.page/news-and-stories/volvo-trucks-magazine/
- After: …
> 688 search using endpoint

- blocks/v2-stories-carousel/v2-stories-carousel.css
Fix #761
Should restore the arrows below the articles carousel on VT homepage to where they were before the release
> Hotfix carousel arrows misalignment 761

- blocks/magazine-articles/magazine-articles.js
The image checker now correctly checks if it is a URL with an image since the link doesn't end in a dot + extension
Also, the author's name comes as an object, not a regular text so now gets the name from the object
Fix #742
- https://742-search-magazine-fix--volvotrucks-na--aemsites.hlx.page/
- Before: https://main--volvotrucks-us--volvogroup.aem.page/
> HotFix: image & author correctly checked
